name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cgbot:$(date +%s)
    - name: Publish Image
      uses: matootie/github-docker@v2.0.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
